# Generated by Django 5.2.8 on 2025-11-21 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('whatsapp_link', models.CharField(blank=True, help_text='opcional: link wa.me para marcar presença', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_story', models.TextField(help_text='Resumo da ação')),
                ('long_story', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='social_actions/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.event')),
                ('social_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.socialaction')),
            ],
        ),
    ]
