# Generated by Django 5.2.8 on 2025-11-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AlterModelOptions(
            name='socialaction',
            options={'ordering': ['-date'], 'verbose_name': 'Ação Social', 'verbose_name_plural': 'Ações Sociais'},
        ),
    ]
